In [ ]:
def f_to_c(f):
    return (f-32)/1.8

def f_to_c_approx(f):
    return (f-30)/2

def get_conversion_table_a():
    convert_list, table = list(range(0,101,10)), []
    for temp in convert_list:
        temp_list = [temp, round(f_to_c(temp),1), round(f_to_c_approx(temp),1)]
        table.append(temp_list)
    return table
    
def get_conversion_table_b():
    convert_list, table = list(range(0,101,10)), [[],[],[]]
    for temp in convert_list:
        table[0].append(temp)
        table[1].append(round(f_to_c(temp),1))
        table[2].append(round(f_to_c_approx(temp)))
    return table

In [ ]:
get_conversion_table_b()

In [ ]:
def max_list(inlist):
    outlist = []
    for lst in inlist:
        outlist.append(max(lst))
    return outlist

In [ ]:
def most_frequent(integers):
    results = {}
    for integer in integers:
        try:
            results[str(integer)]+=1
        except:
            results[str(integer)]=1
    occurences = list(results.values())
    max_value = max(occurences)
    max_index = [i for i,x in enumerate(occurences) if x==max_value]
    max_occur = [int(list(results.keys())[index]) for index in max_index]
    return max_occur

In [ ]:
def diff(p):
    coefficients = [x for x in p.values()]
    powers = [x for x in p.keys()]
    output = {}
    for i,power in enumerate(powers):
        if power-1 > 0:
            output[power-1] = coefficients[i]*power
    print(output)

In [ ]:
p={0:-3, 3:2, 5:-1}
diff(p)

In [154]:
x=[1,2,3]
y=[4,5,6,7]
z=[8,9]

In [155]:
import numpy as np
def meshgrid(x,y,z):
    output = np.zeros( (3,len(y),len(x),len(z)) )
    for j,y_i in enumerate(y):
        for i,x_i in enumerate(x):
            for k,z_i in enumerate(z):
                output[0,j,i,:]=x_i
                output[1,j,:,:]=y_i
                output[2,j,:,k]=z_i
    return output

In [156]:
print(meshgrid(x,y,z))

[[[[1. 1.]
   [2. 2.]
   [3. 3.]]

  [[1. 1.]
   [2. 2.]
   [3. 3.]]

  [[1. 1.]
   [2. 2.]
   [3. 3.]]

  [[1. 1.]
   [2. 2.]
   [3. 3.]]]


 [[[4. 4.]
   [4. 4.]
   [4. 4.]]

  [[5. 5.]
   [5. 5.]
   [5. 5.]]

  [[6. 6.]
   [6. 6.]
   [6. 6.]]

  [[7. 7.]
   [7. 7.]
   [7. 7.]]]


 [[[8. 9.]
   [8. 9.]
   [8. 9.]]

  [[8. 9.]
   [8. 9.]
   [8. 9.]]

  [[8. 9.]
   [8. 9.]
   [8. 9.]]

  [[8. 9.]
   [8. 9.]
   [8. 9.]]]]


In [157]:
def meshgrid(x,y,z):
    output = np.zeros( (3,len(y),len(x),len(z)) )
    for j,y_i in enumerate(y):
        for i,x_i in enumerate(x):
            for k,z_i in enumerate(z):
                output[0,j,i,:]=x_i
                output[1,j,:,:]=y_i
                output[2,j,:,k]=z_i
    return output

In [200]:
def meshgrid(x,y,z):
    output = [[],[],[]]
    output_0, output_1, output_2 = [],[],[]
    x_list, y_list, z_list = [],[],[]
    z_inner = []
    for k,z_i in enumerate(z):
        z_inner.append(z_i)
    for i,x_i in enumerate(x):
        x_list.append([x_i,x_i])
        z_list.append(z_inner)
    for j,y_i in enumerate(y):
        y_inner = [[y_i,y_i] for i in range(len(x))]
        y_list.append(y_inner)
        output_0.append(x_list)
        output_1.append(y_list)
        output_2.append(z_list)
    
    output[0] = output_0
    output[1] = y_list
    output[2] = output_2
    
    return np.array(output)

In [202]:
print(meshgrid(x,y,z).shape)

(3, 4, 3, 2)
