In [4]:
import numpy as np
from itertools import combinations
import pprint

E1 = [1,1,0,1,0,0,0,0,0]
E2 = [1,1,1,0,1,0,0,0,0]
E3 = [0,1,1,0,0,1,0,0,0]
E4 = [1,0,0,1,1,0,1,0,0]
E5 = [0,1,0,1,1,1,0,1,0]
E6 = [0,0,1,0,1,1,0,0,1]
E7 = [0,0,0,1,0,0,1,1,0]
E8 = [0,0,0,0,1,0,1,1,1]
E9 = [0,0,0,0,0,1,0,1,1]


Lst = [E1,E2,E3,E4,E5,E6,E7,E8,E9]
OpLst = []
result=[[]]

In [7]:
for i in Lst:
    OpLst.append(np.array(i))
pprint.pprint(OpLst)

[array([1, 1, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([0, 0, 1, 0, 1, 1, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 1]),
 array([1, 1, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([0, 0, 1, 0, 1, 1, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 1]),
 array([1, 1, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([0, 0, 1, 0, 1, 1, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 1])]


In [21]:
i = 3
Allops = list(combinations(Lst,i))
Allops

[([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 1, 0, 0, 0]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [1, 0, 0, 1, 1, 0, 1, 0, 0]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [0, 1, 0, 1, 1, 1, 0, 1, 0]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [0, 0, 1, 0, 1, 1, 0, 0, 1]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 1, 1, 0]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 1, 1, 1]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [1, 1, 1, 0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 1, 1]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 1, 0, 0, 0],
  [1, 0, 0, 1, 1, 0, 1, 0, 0]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 1, 0, 0, 0],
  [0, 1, 0, 1, 1, 1, 0, 1, 0]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 1, 0, 0, 0],
  [0, 0, 1, 0, 1, 1, 0, 0, 1]),
 ([1, 1, 0, 1, 0, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 1, 0, 0, 0]

In [22]:
for j in Allops:
    index_list = []
    Op = []
    is_interstingconfig = True
    for k in j:
        ind = Lst.index(k)
        index_list.append(ind)
        Op.append(OpLst[ind])
        
    print("Op",Op)
    final_state = sum(Op)
    
    print("final_state",final_state)
    for k in range(len(final_state)):
        if final_state[k] % 2 ==0:
            final_state[k]=0
        elif final_state[k] % 2 == 1:
            final_state[k] = 1
        else:
            print ("Error")

    for k in range(len(final_state)):
        if k in index_list:
            if final_state[k] == 0:
                is_interstingconfig = False
        else:
            if final_state[k] == 1:
                is_interstingconfig = False

    if is_interstingconfig:
        for k in range(len(index_list)):
            index_list[k] += 1
        result.append(index_list)

Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([0, 1, 1, 0, 0, 1, 0, 0, 0])]
final_state [2 3 2 1 1 1 0 0 0]
Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([1, 0, 0, 1, 1, 0, 1, 0, 0])]
final_state [3 2 1 2 2 0 1 0 0]
Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([0, 1, 0, 1, 1, 1, 0, 1, 0])]
final_state [2 3 1 2 2 1 0 1 0]
Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([0, 0, 1, 0, 1, 1, 0, 0, 1])]
final_state [2 2 2 1 2 1 0 0 1]
Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([0, 0, 0, 1, 0, 0, 1, 1, 0])]
final_state [2 2 1 2 1 0 1 1 0]
Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([0, 0, 0, 0, 1, 0, 1, 1, 1])]
final_state [2 2 1 1 2 0 1 1 1]
Op [array([1, 1, 0, 1, 0, 0, 0, 0, 0]), array([1, 1, 1, 0, 1, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 1, 0, 1, 1])]
final_state [2 2 1 1 1 1

In [9]:
print("There are %d intersting configurations"%len(result))
print("They are",result)

There are 1 intersting configurations
They are [[]]
